name: Build and Publish

on:
  push:
    tags:
      - 'alpha/v**'
      - 'beta/v**'
      - 'release/v**'
      - 'test/v**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up OpenJDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin
      - name: Get release type from github tag
        id: get_release_type
        uses: actions/github-script@0.4.0
        with:
          github-token: ${{ secrets.RELEASE_NOTES_TOKEN }}
          result-encoding: string
          script: |
            return '${{ github.ref }}'.match(/refs\/tags\/(.*)\/v((.*)-(.*))/)[1];
      - name: Get file version from tag
        id: get_version
        uses: actions/github-script@0.4.0
        with:
          github-token: ${{ secrets.RELEASE_NOTES_TOKEN }}
          result-encoding: string
          script: |
            return '${{ github.ref }}'.match(/refs\/tags\/(.*)\/v((.*)-(.*))/)[4];
      - name: Get main mc version from tag
        id: get_mc_version
        uses: actions/github-script@0.4.0
        with:
          github-token: ${{ secrets.RELEASE_NOTES_TOKEN }}
          result-encoding: string
          script: |
            return '${{ github.ref }}'.match(/refs\/tags\/(.*)\/v((.*)-(.*))/)[3];
      - name: "Build"
        uses: eskatos/gradle-command-action@v1
        env:
          VERSION: ${{ steps.get_mc_version.outputs.result }}-${{ steps.get_version.outputs.result }}
          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
        with:
          arguments: build --max-workers 1
          distributions-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_NOTES_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: occultism-${{ steps.get_mc_version.outputs.result }}-${{ steps.get_version.outputs.result }}-${{ steps.get_release_type.outputs.result }}
          body: |
            [[Automated Build]]
            Changelog will be added on milestone close.
          draft: false
          prerelease: false
      - name: Upload release asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_NOTES_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/libs/occultism-${{ steps.get_mc_version.outputs.result }}-${{ steps.get_version.outputs.result }}.jar
          asset_name: occultism-${{ steps.get_mc_version.outputs.result }}-${{ steps.get_version.outputs.result }}-${{ steps.get_release_type.outputs.result }}.jar
          asset_content_type: application/java-archive
      - name: Upload to Mod Platforms
        uses: itsmeow/curseforge-upload@master
        with:
          modrinth-id: sbJh4AZw
          modrinth-token: ${{ secrets.MODRINTH_API_KEY }}
          curseforge-id: 361026
          curseforge-token: ${{ secrets.CURSEFORGE_API_KEY }}
          game_endpoint: minecraft
          files: |
            build/libs/occultism-${{ steps.get_mc_version.outputs.result }}-${{ steps.get_version.outputs.result }}.jar
          name: occultism-${{ steps.get_mc_version.outputs.result }}-${{ steps.get_version.outputs.result }}.jar
          version: ${{ steps.get_mc_version.outputs.result }}-${{ steps.get_version.outputs.result }}
          version-type: ${{ steps.get_release_type.outputs.result }}
          game-versions: |
            1.19
            ${{ steps.get_mc_version.outputs.result }}
          changelog: |-
            [Automated Build]
            ${{ steps.get_version.outputs.result }}
            Changelog for this build: https://github.com/klikli-dev/occultism/releases/tag/${{ steps.get_release_type.outputs.result }}%2Fv${{ steps.get_mc_version.outputs.result }}-${{ steps.get_version.outputs.result }}
            Find changes for all versions at https://github.com/klikli-dev/occultism/releases
          game_versions: Forge,Minecraft 1.18:1.18,Minecraft 1.18:${{ steps.get_mc_version.outputs.result }}
          display_name: occultism-${{ steps.get_mc_version.outputs.result }}-${{ steps.get_version.outputs.result }}.jar
          release_type: ${{ steps.get_release_type.outputs.result }}
          dependencies: |
            forge(required)
            modonomicon(required)
            curios(required)
            geckolib(required)
            smartbrainlib(required)
            theurgy(optional)
            jei(optional)
            almost-unified(optional)
            perviaminvenire(optional)
